/* TODO: Remove lint exception */
/* eslint-disable import/prefer-default-export */
export const DEVICE_TYPE = 'DEVICE_TYPE';
export const IS_TABLET = 'IS_TABLET';
export const REGION_TYPE = 'REGION_TYPE';
export const CONFIG_KEYS = 'CONFIG_KEYS';
export const CURRENT_ROUTE = 'CURRENT_ROUTE';
export const PAGE_URL = 'PAGE_URL';
export const PAGE_QUERY = 'PAGE_QUERY';
export const GLOBAL_DATA_FAILURE = 'GLOBAL_DATA_FAILURE';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const SET_USER_STATE = 'SET_USER_STATE';
export const PAGE_ORIGIN = 'PAGE_ORIGIN';

export const USER_STATE_LOGGED_IN = 'LOGGED_IN';
export const USER_STATE_RECOGNIZED = 'RECOGNIZED';
export const USER_STATE_ANONYMOUS = 'ANONYMOUS';
export const UPDATE_SESSION_EMAIL = 'UPDATE_SESSION_EMAIL';
export const GET_APPLICATION_LABELS = '@XT/APP/GET_APPLICATION_LABELS';
export const GET_APPLICATION_LABELS_SUCCESS = '@XT/APP/GET_APPLICATION_LABELS_SUCCESS';
export const GET_APPLICATION_LABELS_FAILURE = '@XT/APP/GET_APPLICATION_LABELS_FAILURE';
